// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"freefrom.space/videoTransform/ent/predicate"
	"freefrom.space/videoTransform/ent/video"
)

// VideoUpdate is the builder for updating Video entities.
type VideoUpdate struct {
	config
	hooks    []Hook
	mutation *VideoMutation
}

// Where appends a list predicates to the VideoUpdate builder.
func (vu *VideoUpdate) Where(ps ...predicate.Video) *VideoUpdate {
	vu.mutation.Where(ps...)
	return vu
}

// SetOriginURL sets the "origin_url" field.
func (vu *VideoUpdate) SetOriginURL(s string) *VideoUpdate {
	vu.mutation.SetOriginURL(s)
	return vu
}

// SetNillableOriginURL sets the "origin_url" field if the given value is not nil.
func (vu *VideoUpdate) SetNillableOriginURL(s *string) *VideoUpdate {
	if s != nil {
		vu.SetOriginURL(*s)
	}
	return vu
}

// SetConvertURL sets the "convert_url" field.
func (vu *VideoUpdate) SetConvertURL(s string) *VideoUpdate {
	vu.mutation.SetConvertURL(s)
	return vu
}

// SetNillableConvertURL sets the "convert_url" field if the given value is not nil.
func (vu *VideoUpdate) SetNillableConvertURL(s *string) *VideoUpdate {
	if s != nil {
		vu.SetConvertURL(*s)
	}
	return vu
}

// ClearConvertURL clears the value of the "convert_url" field.
func (vu *VideoUpdate) ClearConvertURL() *VideoUpdate {
	vu.mutation.ClearConvertURL()
	return vu
}

// Mutation returns the VideoMutation object of the builder.
func (vu *VideoUpdate) Mutation() *VideoMutation {
	return vu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (vu *VideoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, vu.sqlSave, vu.mutation, vu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vu *VideoUpdate) SaveX(ctx context.Context) int {
	affected, err := vu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vu *VideoUpdate) Exec(ctx context.Context) error {
	_, err := vu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vu *VideoUpdate) ExecX(ctx context.Context) {
	if err := vu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (vu *VideoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(video.Table, video.Columns, sqlgraph.NewFieldSpec(video.FieldID, field.TypeInt))
	if ps := vu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vu.mutation.OriginURL(); ok {
		_spec.SetField(video.FieldOriginURL, field.TypeString, value)
	}
	if value, ok := vu.mutation.ConvertURL(); ok {
		_spec.SetField(video.FieldConvertURL, field.TypeString, value)
	}
	if vu.mutation.ConvertURLCleared() {
		_spec.ClearField(video.FieldConvertURL, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, vu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{video.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	vu.mutation.done = true
	return n, nil
}

// VideoUpdateOne is the builder for updating a single Video entity.
type VideoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VideoMutation
}

// SetOriginURL sets the "origin_url" field.
func (vuo *VideoUpdateOne) SetOriginURL(s string) *VideoUpdateOne {
	vuo.mutation.SetOriginURL(s)
	return vuo
}

// SetNillableOriginURL sets the "origin_url" field if the given value is not nil.
func (vuo *VideoUpdateOne) SetNillableOriginURL(s *string) *VideoUpdateOne {
	if s != nil {
		vuo.SetOriginURL(*s)
	}
	return vuo
}

// SetConvertURL sets the "convert_url" field.
func (vuo *VideoUpdateOne) SetConvertURL(s string) *VideoUpdateOne {
	vuo.mutation.SetConvertURL(s)
	return vuo
}

// SetNillableConvertURL sets the "convert_url" field if the given value is not nil.
func (vuo *VideoUpdateOne) SetNillableConvertURL(s *string) *VideoUpdateOne {
	if s != nil {
		vuo.SetConvertURL(*s)
	}
	return vuo
}

// ClearConvertURL clears the value of the "convert_url" field.
func (vuo *VideoUpdateOne) ClearConvertURL() *VideoUpdateOne {
	vuo.mutation.ClearConvertURL()
	return vuo
}

// Mutation returns the VideoMutation object of the builder.
func (vuo *VideoUpdateOne) Mutation() *VideoMutation {
	return vuo.mutation
}

// Where appends a list predicates to the VideoUpdate builder.
func (vuo *VideoUpdateOne) Where(ps ...predicate.Video) *VideoUpdateOne {
	vuo.mutation.Where(ps...)
	return vuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (vuo *VideoUpdateOne) Select(field string, fields ...string) *VideoUpdateOne {
	vuo.fields = append([]string{field}, fields...)
	return vuo
}

// Save executes the query and returns the updated Video entity.
func (vuo *VideoUpdateOne) Save(ctx context.Context) (*Video, error) {
	return withHooks(ctx, vuo.sqlSave, vuo.mutation, vuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vuo *VideoUpdateOne) SaveX(ctx context.Context) *Video {
	node, err := vuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (vuo *VideoUpdateOne) Exec(ctx context.Context) error {
	_, err := vuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vuo *VideoUpdateOne) ExecX(ctx context.Context) {
	if err := vuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (vuo *VideoUpdateOne) sqlSave(ctx context.Context) (_node *Video, err error) {
	_spec := sqlgraph.NewUpdateSpec(video.Table, video.Columns, sqlgraph.NewFieldSpec(video.FieldID, field.TypeInt))
	id, ok := vuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Video.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := vuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, video.FieldID)
		for _, f := range fields {
			if !video.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != video.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := vuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vuo.mutation.OriginURL(); ok {
		_spec.SetField(video.FieldOriginURL, field.TypeString, value)
	}
	if value, ok := vuo.mutation.ConvertURL(); ok {
		_spec.SetField(video.FieldConvertURL, field.TypeString, value)
	}
	if vuo.mutation.ConvertURLCleared() {
		_spec.ClearField(video.FieldConvertURL, field.TypeString)
	}
	_node = &Video{config: vuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, vuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{video.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	vuo.mutation.done = true
	return _node, nil
}
