// Code generated by ent, DO NOT EDIT.

package video

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the video type in the database.
	Label = "video"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOriginURL holds the string denoting the origin_url field in the database.
	FieldOriginURL = "origin_url"
	// FieldConvertURL holds the string denoting the convert_url field in the database.
	FieldConvertURL = "convert_url"
	// Table holds the table name of the video in the database.
	Table = "videos"
)

// Columns holds all SQL columns for video fields.
var Columns = []string{
	FieldID,
	FieldOriginURL,
	FieldConvertURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Video queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOriginURL orders the results by the origin_url field.
func ByOriginURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginURL, opts...).ToFunc()
}

// ByConvertURL orders the results by the convert_url field.
func ByConvertURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConvertURL, opts...).ToFunc()
}
