// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	xy_video "freefrom.space/videoTransform/biz/router/xy/video"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	xy_video.Register(r)
}
